{% set name = "vulkan-memory-allocator" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5e7749504cb802427ffb7bec38a0b6a15db46ae253f00560acb3e624d9fe695c

build:
  number: 0
  script:
    - mkdir -p ${PREFIX}/include/vma                                       # [unix]
    - cp ${SRC_DIR}/include/vk_mem_alloc.h ${PREFIX}/include/vma/          # [unix]
    - mkdir %LIBRARY_PREFIX%\include\vma                                   # [win]
    - copy %SRC_DIR%\include\vk_mem_alloc.h %LIBRARY_PREFIX%\include\vma\  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/vma/vk_mem_alloc.h                       # [unix]
    - if not exist %LIBRARY_PREFIX%\include\vma\vk_mem_alloc.h (exit 1)  # [win]

about:
  home: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
  summary: 'Easy to integrate Vulkan memory allocation library'
  description: |
    Vulkan Memory Allocator (VMA) is a library designed to help developers
    manage memory allocation in Vulkan applications.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/
  dev_url: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator

extra:
  recipe-maintainers:
    - JarrettSJohnson
